module.exports = {
    DEFAULT_BAR_CHASER: '',
    DEFAULT_BAR_COMPLETE_CHARACTER: '\u2588', // █
    DEFAULT_BAR_GLUE: '',
    DEFAULT_BAR_INCOMPLETE_CHARACTER: '\u2591', // ░
    DEFAULT_BAR_SIZE: 40,
    DEFAULT_DURATION_LABEL: '🕒',
    DEFAULT_ETA_LABEL: '⏱️',
    DEFAULT_PROGRESS_DELIMITER: ' | ',
};
